### ISSUE TITLE
Need DB setup howto

### ISSUE THREAD

**Issue by francoisbruneau** [LeBenLeBen/citations#8]
Just completed the steps described in README.md, got the local server running with the following error in Javascript console:

`uncaught exception: Error: Your API key is invalid, please check you have copied it correctly.`

According to https://github.com/LeBenLeBen/citations/blob/master/src/services/firebase.js, there's some environment variables to configure (VUE_APP_FIREBASE_PROJECT_ID and VUE_APP_FIREBASE_API_KEY).

Could a couple of steps be added about how to a create a database for the application which has all the basic collections created (`rails db:setup`equivalent) ?

Thanks!

**Comment by LeBenLeBen** [comment]
@francoisbruneau I updated the readme with more information, hope that helps you finalize your setup. If you encounter any other issue, feel free to reopen.
